<a href="https://colab.research.google.com/github/rpolea/CE888/blob/main/Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib
import pandas as pd
import seaborn as sns
import numpy as np

In [10]:
# Load the data
df = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header = None)
df.head(5)
#df.value_counts

   0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [11]:
 df1 = df.drop(columns = 0)

In [12]:
df1.replace(99, np.nan, inplace=True)

In [13]:
df1.describe()

                1             2    ...           99           100
count  16452.000000  18184.000000  ...  10910.000000  9943.000000
mean       0.904573      0.208460  ...     -0.031244     1.354711
std        5.171798      5.597327  ...      5.176806     5.300409
min       -9.950000     -9.950000  ...     -9.950000    -9.950000
25%       -2.670000     -4.420000  ...     -4.170000    -2.330000
50%        1.600000      0.830000  ...      0.290000     2.140000
75%        4.900000      4.820000  ...      3.980000     5.730000
max        9.370000      9.370000  ...      9.370000     9.370000

[8 rows x 100 columns]

In [15]:
df1.shape

(24983, 100)

In [14]:
df2 = df1.iloc[[4957,79]]
df2

       1     2     3     4     5     6    ...  95   96   97   98   99    100
4957  2.91  0.83  4.47  0.97  1.41  2.18  ...  NaN  NaN  NaN  NaN  NaN -0.49
79     NaN   NaN   NaN   NaN -1.41 -1.31  ...  NaN  NaN  NaN  NaN  NaN   NaN

[2 rows x 100 columns]

In [ ]:
arr = df.values
print(arr.shape)

(24983, 101)

In [ ]:
arr

array([[ 74.  ,  -7.82,   8.79, ...,    nan,    nan,    nan],
       [100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,    nan,    nan, ...,    nan,    nan,    nan],
       ...,
       [ 39.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 37.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 72.  ,   2.43,   2.67, ...,    nan,    nan,    nan]])

In [ ]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2523283 (2523283,)

In [ ]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:
rated = np.where(arr!=99)

In [ ]:
new_arr, idx = replace(arr, 0.1)

In [ ]:
arr[idx[0][0], idx[1][0]]

0.15

In [ ]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [ ]:
df.replace(99, np.nan, inplace=True)

In [ ]:
print(new_arr)

[[ 74.    -7.82   8.79 ...    nan    nan    nan]
 [100.     4.08  -0.29 ...   0.34  -4.32   1.07]
 [ 49.      nan    nan ...    nan    nan    nan]
 ...
 [ 99.      nan    nan ...    nan    nan    nan]
 [ 37.      nan    nan ...    nan    nan    nan]
 [ 72.     2.43   2.67 ...  99.      nan    nan]]